services:
  postgres:
    image: postgres:alpine
    container_name: bsn-db
    environment:
      POSTGRES_USER: pvhg
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-network
    restart: unless-stopped

  mail-service:
    image: maildev/maildev
    container_name: mail-dev-bsn
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  spring-network:
    driver: bridge

volumes:
  postgres:
    driver: local